default_language_version:
  python: python3

repos:
  # Waiting on Hop311 to approve clang-format
  # - repo: https://github.com/pre-commit/mirrors-clang-format
  #   rev: v19.1.3
  #   hooks:
  #     - id: clang-format
  #       files: \.(c|h|cpp|hpp|inc)$
  #       types_or: [text]
  #       # exclude: |
  #       #   (?x)^(
  #       #   )

  - repo: https://github.com/pocc/pre-commit-hooks
    rev: v1.3.5
    hooks:
      - id: clang-tidy
        files: \.(c|h|cpp|hpp|inc)$
        args: [--fix, --quiet, --use-color]
        types_or: [text]
        additional_dependencies: [clang-tidy==19.1.0]
        require_serial: true
        stages: [manual] # Not automatically triggered, invoked via `pre-commit run --hook-stage manual clang-tidy`

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.7.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        # exclude: |
        #   (?x)^(
        #   )

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.13.0
    hooks:
      - id: mypy
        files: \.py$
        types_or: [text]

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        # exclude: |
        #   (?x)^(
        #   )
        additional_dependencies: [tomli]